# Define pipeline paths
# datapath: /home/camp/capitac/working/charlotte/rnaSeq_pipeline/
datapath: /home/camp/chakraa2/working/nobby/projects/snakemake/

# Define samples
# samples:
#     m62ahek_ready2map: m62ahek_ready2map

samples:
    ENCFF000DMU,
    ENCFF000DMU2

# Indices
bt2_rRNA_tRNA_index: /home/camp/chakraa2/working/nobby/genomes/index/bt2_rRNA_tRNA/rRNA_tRNA
star_index: /home/camp/chakraa2/working/nobby/genomes/index/STAR_GRCh38_Gencode25

# Define paramaters
trim_galore_params:
    True
