# Define pipeline paths
global:
  snakemake: /path/to/RNA-seq-pipeline/src # Folder containing Snakemake file, executables and scripts folders
  results: /path/to/RNA-seq-pipeline/results # Folder where the outputs will be placed
  remove_duplicates: true # Either 'true' or 'false'

# Define barcode (B) and UMI (U) pattern at the 5'-end of the read
barcode: "UUUBBBBBUUU" # Either a string of 'B's and/or 'U's or 'false'

# Define mapping and annotation paths
genome:
  path: /path/to/genome # Folder containing the genome file
  name: GRCh38.primary_assembly.genome.fa.gz # FASTA file (can be gzipped)
annotation:
  path: /path/to/annotation # Folder containing the annotation file
  name: gencode.v27.annotation.gtf.gz # GTF or GFF3 file (can be gzipped)
alignment:
  path: /path/to/genome # Folder containing the index files
  ribo: human_rRNA_tRNA/rRNA_tRNA # Bowtie2 index basename or FASTA file (can be gzipped; the index will be created)
  star: STAR_GRCh38_v27 # Folder containing the STAR index (it will be created)

# Define samples (multiple experiments and library types can be specified in the same config file)
samples:
  Single-end_sample: ["/path/to/RNA-seq-pipeline/data/single.fastq.gz"] # Example of single-end experiment
  Paired-end_sample: ["/path/to/RNA-seq-pipeline/data/paired_1.fastq.gz", "/path/to/RNA-seq-pipeline/data/paired_2.fastq.gz"] # Example of paired-end experiment

# Define sequencing type
seq_type: "RNAseq" # RNAseq or NETseq (NETseq will not allow spliced reads alignment)
