# Define pipeline paths
global:
  snakemake: /Users/agostif/Documents/GitHub/RNA-seq-pipeline/src
  results: /Users/agostif/Documents/GitHub/RNA-seq-pipeline/results

# Define mapping and annotation paths
genome:
  path: /Users/agostif/Documents/GitHub/RNA-seq-pipeline/src/genome
  name: GRCh38.primary_assembly.genome.fa.gz
annotation:
  path: /Users/agostif/Documents/GitHub/RNA-seq-pipeline/src/annotation
  name: gencode.v27.annotation.gtf.gz
alignment:
  path: /Users/agostif/Documents/GitHub/RNA-seq-pipeline/src/genome
  ribo: human_rRNA_tRNA/rRNA_tRNA
  star: STAR_GRCh38_v27

# Define samples
samples:
  Single-end_sample: ["/Users/agostif/Documents/GitHub/RNA-seq-pipeline/data/single.fastq.gz"] # Single-end sample
  Paired-end_sample: ["/Users/agostif/Documents/GitHub/RNA-seq-pipeline/data/paired_1.fastq.gz", "/Users/agostif/Documents/GitHub/RNA-seq-pipeline/data/paired_2.fastq.gz"] # Paired-end sample

# Define sequencing type
seq_type: "RNAseq" # or NETseq or GROseq (not implemented yet)
