sample_id: 'ENCFF000DMW'

bt2_rRNA_tRNA_index: /home/camp/chakraa2/working/nobby/genomes/index/bt2_rRNA_tRNA/rRNA_tRNA
star_index: /home/camp/chakraa2/working/nobby/genomes/index/STAR_GRCh38_Gencode25
